Create stale.yml
qa-brasil/vagas pull request #1084
Opened 2022-11-02 07:42 UTC by guibranco

Cria uma action para fechar as issues que estão abertas a mais de 60 dias sem atualizações. Isso ajuda a manter as vagas ativas e atualizadas.
Existem issues abertas desde Janeiro 2020 como #3

2022-11-02 18:09 UTC, guibranco commented
@brunopulis

2022-11-03 19:44 UTC, brunopulis commented
Opa @guibranco, excelente ideia hoje mais a noite irei olhar o PR.

2022-11-06 16:12 UTC, PauloGoncalvesBH requested changes
Gostei da sugestão de encerrar issues abertas por inatividade, porém é importante que ao fechar a issue nenhuma mensagem seja incluída na issue pois isso vai gera spam para todas as 364 pessoas que recebem as interações da issues por e-mail.
É importante evitar ao máximo qualquer notificação que não seja de abertura de issue com nova vaga.

2022-11-06 16:56 UTC, guibranco commented
> Gostei da sugestão de encerrar issues abertas por inatividade, porém é importante que ao fechar a issue nenhuma mensagem seja incluída na issue pois isso vai gera spam para todas as 364 pessoas que recebem as interações da issues por e-mail. Precisamos evitar ao máximo qualquer notificação que não seja de abertura de issue com nova vaga.

Removi a mensagem que informa que a issue será fechada em X dias, agora nenhum "comentário" será adicionado a issue. 
Apenas a label "stale" e depois de X dias (5 no caso) será fechada.
Com isso não será enviado notificação para quem está subscrito.

2022-11-06 23:01 UTC, brunopulis approved these changes

2022-11-09 12:05 UTC, merged